M48
; DRILL file {KiCad 6.0.1-79c1e3a40b~116~ubuntu20.04.1} date jue 20 ene 2022 10:05:29
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-01-20T10:05:29+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.1-79c1e3a40b~116~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.100
%
G90
G05
T1
X144.05Y-76.698
X144.05Y-81.298
T0
M30
