M48
; DRILL file {KiCad 6.0.1-79c1e3a40b~116~ubuntu20.04.1} date lun 17 ene 2022 20:41:11
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-01-17T20:41:11+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.1-79c1e3a40b~116~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.100
%
G90
G05
T1
X145.25Y-76.47
X145.25Y-81.07
T0
M30
