/*
 * GENERATED BY wfof_gen v2.0 on 03/12/2017 23:57:11
 *
 * Created by Martin Winkelhofer 02,03,04,11/2016
 * W-Dimension / wdim / wdim0 / winkelhofer.m@gmail.com / https://github.com/wdim0
 *    _____ __          ____         ______         __
 *   / __(_) /__ ___   / __ \___    / __/ /__ ____ / /
 *  / _// / / -_|_-<  / /_/ / _ \  / _// / _ `(_-</ _ \
 * /_/ /_/_/\__/___/  \____/_//_/ /_/ /_/\_,_/___/_//_/
 *
 * System for compiling binary data of files in specific directory (wfof/content) as a part of
 * program data -> will be written to Flash memory + system of functions for reading it.
 * v2.01 (11/2016)
 *
 * This file is part of WFOF - W-Dimension's Files On Flash for ESP8266.
 *
 * WFOF is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * WFOF is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with WFOF. If not, see <http://www.gnu.org/licenses/>.
 */
#ifndef __WFOF_IDXS_H__
#define __WFOF_IDXS_H__

#define WFOF_FILES_CNT		20

#define WFOF_ALIGN_BYTES		4

#define WFOF_IDX_AUTO_PNG_BMP_16BPP		0
#define WFOF_IDX_BROKER_PNG_BMP_16BPP		1
#define WFOF_IDX_BROKEROFF_PNG_BMP_16BPP		2
#define WFOF_IDX_CLOCKERROR_PNG_BMP_16BPP		3
#define WFOF_IDX_CLOCKEXPIRED_PNG_BMP_16BPP		4
#define WFOF_IDX_CLOCKONTIME_PNG_BMP_16BPP		5
#define WFOF_IDX_CLOCKSETTINGS_PNG_BMP_16BPP		6
#define WFOF_IDX_HANDX32_PNG_BMP_16BPP		7
#define WFOF_IDX_HUMEDAD_PNG_BMP_16BPP		8
#define WFOF_IDX_OFF_PNG_BMP_16BPP		9
#define WFOF_IDX_ON_PNG_BMP_16BPP		10
#define WFOF_IDX_RECEIVING_PNG_BMP_16BPP		11
#define WFOF_IDX_RELE_PNG_BMP_16BPP		12
#define WFOF_IDX_RESET_PNG_BMP_16BPP		13
#define WFOF_IDX_SKULL_PNG_BMP_16BPP		14
#define WFOF_IDX_TERMOMETRO_PNG_BMP_16BPP		15
#define WFOF_IDX_TRANSFER_PNG_BMP_16BPP		16
#define WFOF_IDX_WIFIOFF_PNG_BMP_16BPP		17
#define WFOF_IDX_WIFION_PNG_BMP_16BPP		18
#define WFOF_IDX_WIFISETTINGS_PNG_BMP_16BPP		19

#define WFOF_SIZE_AUTO_PNG_BMP_16BPP		607
#define WFOF_SIZE_BROKER_PNG_BMP_16BPP		664
#define WFOF_SIZE_BROKEROFF_PNG_BMP_16BPP		703
#define WFOF_SIZE_CLOCKERROR_PNG_BMP_16BPP		994
#define WFOF_SIZE_CLOCKEXPIRED_PNG_BMP_16BPP		994
#define WFOF_SIZE_CLOCKONTIME_PNG_BMP_16BPP		931
#define WFOF_SIZE_CLOCKSETTINGS_PNG_BMP_16BPP		2917
#define WFOF_SIZE_HANDX32_PNG_BMP_16BPP		883
#define WFOF_SIZE_HUMEDAD_PNG_BMP_16BPP		778
#define WFOF_SIZE_OFF_PNG_BMP_16BPP		1573
#define WFOF_SIZE_ON_PNG_BMP_16BPP		2344
#define WFOF_SIZE_RECEIVING_PNG_BMP_16BPP		187
#define WFOF_SIZE_RELE_PNG_BMP_16BPP		352
#define WFOF_SIZE_RESET_PNG_BMP_16BPP		2824
#define WFOF_SIZE_SKULL_PNG_BMP_16BPP		10
#define WFOF_SIZE_TERMOMETRO_PNG_BMP_16BPP		487
#define WFOF_SIZE_TRANSFER_PNG_BMP_16BPP		187
#define WFOF_SIZE_WIFIOFF_PNG_BMP_16BPP		526
#define WFOF_SIZE_WIFION_PNG_BMP_16BPP		205
#define WFOF_SIZE_WIFISETTINGS_PNG_BMP_16BPP		3181

#endif
