/*
 * errores_proyecto.h
 *
 *  Created on: 15 sept. 2020
 *      Author: t126401
 */

#ifndef COMPONENTS_COMUNES_INCLUDE_ERRORES_PROYECTO_H_
#define COMPONENTS_COMUNES_INCLUDE_ERRORES_PROYECTO_H_


#define	RESULTADO_OK  200
#define RESULTADO_NOK 500
	//ERRORES WIFI
#define	WIFI_OK 220
#define	WIFI_NOK 520
	//ERRORES MQTT
#define	MQTT_OK 230
#define	MQTT_NOK 530
	//ERRORES JSON
#define	JSON_OK 240
#define	JSON_NOK 540
#define JSON_NOK_PRINT 541
	//ERRORES CONFIGURACION
#define	CONFIGURACION_OK 250
#define	CONFIGURACION_NOK 550

// ERRORES PROGRAMA
#define PROGRAMACION_OK 260
#define PROGRAMACION_NOK 560
#define PROGRAMACION_NO_EXISTE 561
#define PROGRAMACION_DURACION_EXCEDIDA 562

#define RELOJ_OK 600
#define RELOJ_SIN_HORA 601

#define NVS_OK 700
#define INICIALIZAR_NVS_NOK 701



#endif /* COMPONENTS_COMUNES_INCLUDE_ERRORES_PROYECTO_H_ */
