/*
 * GENERATED BY wfof_gen v2.0 on 18/10/2017 0:47:12
 *
 * Created by Martin Winkelhofer 02,03,04,11/2016
 * W-Dimension / wdim / wdim0 / winkelhofer.m@gmail.com / https://github.com/wdim0
 *    _____ __          ____         ______         __
 *   / __(_) /__ ___   / __ \___    / __/ /__ ____ / /
 *  / _// / / -_|_-<  / /_/ / _ \  / _// / _ `(_-</ _ \
 * /_/ /_/_/\__/___/  \____/_//_/ /_/ /_/\_,_/___/_//_/
 *
 * System for compiling binary data of files in specific directory (wfof/content) as a part of
 * program data -> will be written to Flash memory + system of functions for reading it.
 * v2.01 (11/2016)
 *
 * This file is part of WFOF - W-Dimension's Files On Flash for ESP8266.
 *
 * WFOF is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * WFOF is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with WFOF. If not, see <http://www.gnu.org/licenses/>.
 */
#ifndef __WFOF_IDXS_H__
#define __WFOF_IDXS_H__

#define WFOF_FILES_CNT		7

#define WFOF_ALIGN_BYTES		4

#define WFOF_IDX_WIFI_OFF_PNG_BMP_16BPP		0
#define WFOF_IDX_WIFI_PNG_BMP_16BPP		1
#define WFOF_IDX_RAIN_PNG_BMP_16BPP		2
#define WFOF_IDX_LINK_PNG_BMP_16BPP		3
#define WFOF_IDX_TEMPERATURE_PNG_BMP_16BPP		4
#define WFOF_IDX_FIRE_PNG_BMP_16BPP		5
#define WFOF_IDX_BROKEN_LINK_PNG_BMP_16BPP		6

#define WFOF_SIZE_WIFI_OFF_PNG_BMP_16BPP		529
#define WFOF_SIZE_WIFI_PNG_BMP_16BPP		1330
#define WFOF_SIZE_RAIN_PNG_BMP_16BPP		964
#define WFOF_SIZE_LINK_PNG_BMP_16BPP		1255
#define WFOF_SIZE_TEMPERATURE_PNG_BMP_16BPP		2248
#define WFOF_SIZE_FIRE_PNG_BMP_16BPP		1402
#define WFOF_SIZE_BROKEN_LINK_PNG_BMP_16BPP		871

#endif
